### ISSUE TITLE
Properly exit Splash

### ISSUE THREAD

**Issue by T4g1** [Byteron/floating-islands#19]
E 0:00:09:0293   resume: Resumed function '_animate()' after yield, but class instance is gone. At script: res://source/menu/Splash.gd:30
  <C++ Error>    Method/Function Failed, returning: Variant()
  <C++ Source>   modules/gdscript/gdscript_function.cpp:1840 @ resume()

**Comment by Byteron** [comment]
Uh lemme fix this.
